### ISSUE TITLE
modeling of a switch

### ISSUE THREAD

**Issue by zmladen** [giaccone/SpicePy#1]
Hello Mr. Giaccone,

is it possible to model a switch in spicePy? My goal is to model a buck converter circuit with spicePy.

Thanks,
Mladen

**Comment by giaccone** [comment]
Dear Mladen,
I did not notice this message here but we discussed this issue by email. To close the issue I repeat the same thing that I said two years ago.


> Thanks for you interest in the project. I’m sorry to say that the simulation of your interest is currently not supported by SpicePy because:
> * SpicePy does not have a switch model (neither real nor ideal)
> * SpicePy does not have a non-linear solver
> 
> Maybe in the future I will include also these feature, but not soon for sure.
> SpicePy is born to cover basic circuits that I teach to my students.

**Comment by giaccone** [comment]
Issue closed because it refers to a missing feature that it's not planned to be implemented soon.
